title: Hi, this is Randi
logo: /assets/img/Randi Eka Sanjaya_photo.png
description: >
  Hi, I am data scientist in Information and Communication Technology (ICT) industry, filled with several big data projects and backend developer for big data analytics tools. 
  Skilled in Big Data Analytics, Software Development, and MLOps. Engineering professional with master's degree in industrial engineering focused on business analytics.
#show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
