title: Randi Portfolio
description: Welcome to my portfolio, I am data scientist in ICT industry with master's degree in industrial engineering focused on business analytics.
#show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
